# CityBikes

Send a request to CityBikes for the city of your choice.

In [1]:
import requests
import pandas as pd

# URL to be requested
request_url = "http://api.citybik.es/v2/networks/nextbike-glasgow"

# Perform the API call
response = requests.get(request_url)

# 200 = Success; 404 = Not Found
print(response)

# Display the raw JSON data
# print(response.json()['network']) - Commented out, output too long for GitHub

<Response [200]>

Put your parsed results into a DataFrame.

In [2]:
# NOTE: I re-arranged this and the next step. Unsure if that was an acceptable way of doing it

# Load the station data from the JSON response into the pandas dataframe
all_station_data = pd.json_normalize(response.json()['network']['stations'])

all_station_data

,empty_slots,free_bikes,id,latitude,longitude,name,timestamp,extra.bike_uids,extra.number,extra.slots,extra.uid
0,2.0,7,af1d0f25cbc75377878349fde4d86133,55.858167,-4.245483,Merchant Square - ELECTRIC,2023-09-03T17:54:57.846000Z,"[23644, 47160, 840006, 46768, 46660, 46654, 46...",8407,8.0,264293
1,7.0,1,71b02b6f26f03e58c97dec1e1c9faa00,55.878278,-4.288487,Botanic Gardens - ELECTRIC,2023-09-03T17:54:57.854000Z,[46563],8417,8.0,264302
2,0.0,7,fa6bc682e8627d66891c2b6250c81b1e,55.864788,-4.271852,Mitchell Library,2023-09-03T17:54:57.860000Z,"[47012, 47510, 46949, 46651, 46422, 829267, 82...",8425,6.0,264308
3,2.0,1,a087989280fd941fd9c41c3e787940ae,55.862983,-4.241000,University of Strathclyde (North),2023-09-03T17:54:57.861000Z,[21013],8424,3.0,264309
4,3.0,5,eb47a36e3d5fe5bc456397413bd2aa75,55.852500,-4.258850,Bridge Street Subway - ELECTRIC,2023-09-03T17:54:57.862000Z,"[46993, 46734, 47918, 47968, 829168]",8432,5.0,264316
...,...,...,...,...,...,...,...,...,...,...,...
102,9.0,1,2c49302c8bb3a00373f898594228a941,55.847638,-4.202957,London Road Central,2023-09-03T17:54:57.975000Z,[47952],8474,10.0,213996907
103,0.0,14,d9eacbf78518d186400386d90f0cf49c,55.875865,-4.319601,Broomhill Cross,2023-09-03T17:54:57.976000Z,"[47091, 47041, 47844, 46972, 46876, 46755, 466...",8480,10.0,213997157
104,5.0,5,f6210447e1724487afe0ce63b011aecd,55.895974,-4.354877,Knightswood Park,2023-09-03T17:54:57.974000Z,"[210166, 46858, 47910, 829096, 829050]",8473,10.0,213996668
105,0.0,8,3860eb7809fcced150d10d78ca2a165c,55.862838,-4.341885,"University Hospital, Queen Eliza",2023-09-03T17:54:57.891000Z,"[47097, 46848, 46759, 46680, 46617, 46498, 464...",8450,8.0,751103
106,6.0,5,ed8440d874a0b4205ddbcc0bc56f3d49,55.846362,-4.208322,Emirates Arena,2023-09-03T17:54:57.864000Z,"[81100, 46950, 46917, 46571, 46556]",8428,12.0,266166

Parse through the response to get the details you want for the bike stations in that city (latitude, longitude, number of bikes).

In [3]:
# Rename a few columns to make them less ambigious
all_station_data.rename(columns={'id':'station_id'}, inplace=True)
all_station_data.rename(columns={'name':'station_name'}, inplace=True)

# Copy the chosen columns into a new dataframe
selected_station_data = all_station_data[['station_id','station_name','free_bikes','empty_slots','latitude','longitude']].copy()

selected_station_data

,station_id,station_name,free_bikes,empty_slots,latitude,longitude
0,af1d0f25cbc75377878349fde4d86133,Merchant Square - ELECTRIC,7,2.0,55.858167,-4.245483
1,71b02b6f26f03e58c97dec1e1c9faa00,Botanic Gardens - ELECTRIC,1,7.0,55.878278,-4.288487
2,fa6bc682e8627d66891c2b6250c81b1e,Mitchell Library,7,0.0,55.864788,-4.271852
3,a087989280fd941fd9c41c3e787940ae,University of Strathclyde (North),1,2.0,55.862983,-4.241000
4,eb47a36e3d5fe5bc456397413bd2aa75,Bridge Street Subway - ELECTRIC,5,3.0,55.852500,-4.258850
...,...,...,...,...,...,...
102,2c49302c8bb3a00373f898594228a941,London Road Central,1,9.0,55.847638,-4.202957
103,d9eacbf78518d186400386d90f0cf49c,Broomhill Cross,14,0.0,55.875865,-4.319601
104,f6210447e1724487afe0ce63b011aecd,Knightswood Park,5,5.0,55.895974,-4.354877
105,3860eb7809fcced150d10d78ca2a165c,"University Hospital, Queen Eliza",8,0.0,55.862838,-4.341885
106,ed8440d874a0b4205ddbcc0bc56f3d49,Emirates Arena,5,6.0,55.846362,-4.208322

In [4]:
# Export the data into a CSV for use in other notebooks
selected_station_data.to_csv('../data/citybike_stations.csv', index=False)